### ISSUE TITLE
Unsupported config for services "Prysm" for sepolia

### ISSUE THREAD

**Issue by AtHeartEngineer** [wmitsuda/one-liner-archive#1]
ERROR: The Compose file './sepolia.yml' is invalid because:
Unsupported config option for services: 'prysm'

This is what I ran:
`ERIGON_DATA="/eth/sepolia/erigon" PRYSM_DATA="/eth/sepolia/prysm" docker-compose -f sepolia.yml up`

**Comment by wmitsuda** [comment]
that's strange, it's similar to what I run myself, which docker-compose version are you running?

mine:

```
$ docker-compose -v
docker-compose version 1.29.2, build 5becea4c
```

**Comment by wmitsuda** [comment]
BTW, I just pushed an updated sepolia.yml, I made prysm work (the previous revision had it disabled), if it was something with profiles, I've removed it.

**Comment by jimwavefive** [comment]
I was on compose 1.29, upgrading solved this issue for me

**Comment by AtHeartEngineer** [comment]
I'm on `1.25`, I'll try upgrading. Thanks!

**Comment by AtHeartEngineer** [comment]
Just incase anyone else is having this fun issue. If you install `docker-compose` from apt on `ubuntu 20.04`, you get version `1.25`, but you don't need that `docker-compose`.

If you just remove the `-` between `docker` and `compose` you will use the new docker-compose-plugin that's built into docker, and its using the actual latest version `2.6`
