### ISSUE TITLE
Some problems with ropsten

### ISSUE THREAD

**Issue by Duanraudon** [wmitsuda/one-liner-archive#2]
I used the ropsten configuration file to start the synchronization node, and now the following error appears in the erigon log, how can I solve it?

[WARN] [06-27|02:42:52.858] Served                                   conn=193.56.29.33:54950 method=parity_netPeers reqid=3 t=15.41µs err="the method parity_netPeers does not exist/is not available"
[WARN] [06-27|02:42:52.858] Served                                   conn=193.56.29.33:54948 method=admin_peers reqid=3 t=23.14µs err="the method admin_peers does not exist/is not available"

**Comment by wmitsuda** [comment]
there is some application trying to connect to your node, maybe yours? if not, is the node exposed to internet? it maybe someone scanning for open nodes.

**Comment by Duanraudon** [comment]
time="2022-06-27 05:03:32" level=info msg="Connected to new endpoint: http://erigon:8551" prefix=powchain
time="2022-06-27 05:03:47" level=info msg="Connected to new endpoint: http://erigon:8551" prefix=powchain
time="2022-06-27 05:04:02" level=info msg="Connected to new endpoint: http://erigon:8551" prefix=powchain
time="2022-06-27 05:04:17" level=info msg="Connected to new endpoint: http://erigon:8551" prefix=powchain
time="2022-06-27 05:04:32" level=info msg="Connected to new endpoint: http://erigon:8551" prefix=powchain
time="2022-06-27 05:04:32" level=info msg="Currently waiting for chainstart" Additional validators needed=98829 prefix=powchain

Is it a consensus client?

**Comment by Duanraudon** [comment]
> there is some application trying to connect to your node, maybe yours? if not, is the node exposed to internet? it maybe someone scanning for open nodes.

time="2022-06-27 05:03:32" level=info msg="Connected to new endpoint: http://erigon:8551/" prefix=powchain
time="2022-06-27 05:03:47" level=info msg="Connected to new endpoint: http://erigon:8551/" prefix=powchain
time="2022-06-27 05:04:02" level=info msg="Connected to new endpoint: http://erigon:8551/" prefix=powchain
time="2022-06-27 05:04:17" level=info msg="Connected to new endpoint: http://erigon:8551/" prefix=powchain
time="2022-06-27 05:04:32" level=info msg="Connected to new endpoint: http://erigon:8551/" prefix=powchain
time="2022-06-27 05:04:32" level=info msg="Currently waiting for chainstart" Additional validators needed=98829 prefix=powchain

Is it a consensus client?

**Comment by wmitsuda** [comment]
it is. it's prysm connecting to erigon via inter-container network, that one is normal and expected.

**Comment by wmitsuda** [comment]
I'm reopening this, I think there is a misconfiguration for ropsten (genesis state file missing).

I had a similar issue syncing sepolia from scratch.
